### ISSUE TITLE
Application name contains brand name

### ISSUE THREAD

**Issue by bbhtt** [flathub/me.timschneeberger.GalaxyBudsClient#5]
Hello we are tracking a bunch of applications with trademark violations or ones that contain brand names of other companies.

The current application name contains "Galaxy Buds" which is something used by Samsung for their products and services.

Please try to use your name for the application to avoid trademark issues and confusing people. I think 2 months is a reasonable time period for us to wait for the name to be changed.

You can find some resources for application names in https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines#app-name

And the guidelines on trademarks https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines#no-trademark-violations

**Comment by j-px** [comment]
@timschneeb any idea what to do?

**Comment by timschneeb** [comment]
I've updated the metadata file (https://github.com/timschneeb/GalaxyBudsClient/commit/ff23d4a447c59d169b0895b82c38b2aa01bb35b1) to use 'Earbud manager for Galaxy Buds' as the title and 'An unofficial app to manage any Galaxy Buds device manufactured by Samsung' as the summary.

The 'X for brand' naming scheme, in combination with that summary, seems to be the easiest way to make clear that the software is 3rd-party. If the title is too long or confusing, I can chop the 'for Galaxy Buds' part off as well.

Either way, I currently need to wait for the next stable version of [Avalonia](https://github.com/AvaloniaUI/Avalonia) to be released before I can publish an update with the new metadata due to some critical bug fixes in that library.

**Comment by bbhtt** [comment]
> Either way, I currently need to wait for the next stable version of [Avalonia](https://github.com/AvaloniaUI/Avalonia) to be released before I can publish an update with the new metadata due to some critical bug fixes in that library.

Thanks, that's fine.

**Comment by bbhtt** [comment]
Any update here? I see Avalonia 11.0.11was released last month.

**Comment by timschneeb** [comment]
I've updated the package to v5.1.0 which includes the new app name without brand issues: #6
